### PR TITLE
 "GetRecordOnce" instead of "InsertIfNotExists"

### PR DESCRIPTION
**Pull request by StefanMaron**
Call "InsertIfNotExists" from "GetRecordOnce" and call "GetRecordOnce" from the OnOpenPage Trigger on the Setup page

### CODE REVIEW

**Comment by waldo1001** [comment]
Hm, I see where you're getting at .. but .. isn't this a bit mixing responsibilities?  The page doesn't need to get - it needs to insert if it doesn't exist.  Get happens when opening the page .. so as such, now it would get twice?

During business logic, I could "GetOnce" .. but now it's going to insert, while I might want an error of the get fails (which I do ..) :-/

**Comment by StefanMaron** [comment]
On the OnOpenPage I am with you. Get happens anyway.

But in code, You dont want to get an error if the get fails. You want to get the error on the TestField when your field is empty. As this needs to be checked anyways, the record can automatically be insertert and geted only once :)

**Comment by waldo1001** [comment]
Well .. I don't fully agree, sorry :(.

Most of the time, you're right.  But it's those other times - where:
- I might rely on the fact there is no record in the setup in my business logic
- I might not have permission to write into the setup table

With both separate functions, I have full flexibility: I can choose between both for the behavior that I want.. .

**Comment by StefanMaron** [comment]
I mean, at the end its still your snippet ;) But you agree with my way most of the time, and dont have a function for this case.
Maybe:

- GetRecordOnce -> Error if not exists
- InsertIfNotExists -> Autoinsert and also checks if already getted

this way I could use InsertIfNotExists just all the time if I just want to have the record read to my variable

**Comment by waldo1001** [comment]
Let's agree to disagree ;-).  And I blame my autistic mind .. 

calling "InsertIfNotExists" .. means that I expect it to just insert if not exist - and I intentionally want to insert a record.  That's my intention.
When GetRecordOnce - I'm only interested in getting it.  If it mysteriously would insert it .. that would be unintentional .. and .. yeah .. I would call both, you know?

Sorry :(.  We're talking peanuts here, I know :(.

**Comment by StefanMaron** [comment]
No need to apologize :D I like to discuss even the little things.

But InsertIfNotExists also gets the record. Shouldnt it be setting "RecordHasBeenRead := true;" ? 
If yes then this would fit for me to not do unnecessary reads

**Comment by waldo1001** [comment]
Now THAT I get!  It actually has to , yes .. PR? ;-)

**Comment by StefanMaron** [comment]
of course but this needs to wait a bit ;) currently quite busy :/

**Comment by StefanMaron** [comment]
ehm, what about smth like this?
image

But it seems like this function does only exist on RecordRefs

**Comment by waldo1001** [comment]
Well .. I don't know. 
get GetRecordOnce happens when Record-var is active .. which is usually within a transaction.  Within a page, this doesn't have too much use I guess.. .
Within a transaction - how can this rec get dirty? 🤔

**Comment by StefanMaron** [comment]
Sorry for delay :)

I admit chances are probably very low, but you can always have a second session which updates the rec after you have read it.
If you record variable is global and your code takes some time and later on uses the setup again, chances will rise

**Comment by waldo1001** [comment]
Afaik, it's in the snippet .. sorry for this to take so long.. :(

**Pull request closed without merging**
