### PR TITLE
Added new Guided Experience (Assisted Setup) Snippet

### PR DESCRIPTION
**Pull request by christianbraeunlich**
This PR attempts to add a new Snippet which is based on the Assisted Setup Snippets.

The new Snippet uses the Guided Experience Codeunit in favor of the "Assisted Setup" Codeunit.

Please try this Snippet on your own and provide some feedback. Thanks in advance.

EDIT: Site note - for the future I would recommend to create a new file called `Onboarding.json` and put the related Snippets into that file instead of the `DesignPatterns.json`.

### CODE REVIEW

**Comment by waldo1001** [comment]
Lol, I didn't notice the url :-).  But sure - love it 🤣.
ok for the filenames and moving the snippets - makes lots of sense!
I'm not completely sure about the guidedexperience-methods .. not using that myself (yet).  I'd just leave it as is ..

**Comment by christianbraeunlich** [comment]
Tested the behavior with simple xliff translation and it looks good to me overall. So that's when I decided to remove that bit of translation logic. Feel free to correct me on this one.

**Comment by christianbraeunlich** [comment]
Found a mistake by me: the package.json has to be extended by the new snippet file will add this later this day ...

**Comment by christianbraeunlich** [comment]
What do you think? Is this PR now complete or shall we add some more things for the new "Guided Experience" assisted setup?

**Comment by waldo1001** [comment]
Let's gather info on the people using it ;-).

**Pull request merged**
