### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by christianbraeunlich**
This PR attempts to update the `README.md` file with some additional content:

- Adding Badges with Insights from VS Code Marketplace.
- License section at the end of the file
- Applying some Markdown rules (see: [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint))

btw: feel free to close this PR if this is too much or not in your interest 🦦

### CODE REVIEW

**Comment by christianbraeunlich** [comment]
What do you think about using this background image (https://pbs.twimg.com/media/FTBJk7NWIAAe-WT?format=jpg&name=small) as a logo for this package? Or putting it at the top of the `README.md` file.

**Comment by waldo1001** [comment]
What do you mean?  "Performance Profiling" doesn't really have anything to do with this ;-)

**Comment by christianbraeunlich** [comment]
> What do you mean? "Performance Profiling" doesn't really have anything to do with this ;-)

Without that specific title. I like the background image with the clouds. It adds that little something to this repo because of "Cloud.Ready." - just a thought. It would replace the simple logo provided in this PR on top of the `README.md`.

What do you think about the changes in this PR so far - yay or nay?

**Comment by waldo1001** [comment]
Rest of the changes - yay!
shall I merge?

**Comment by christianbraeunlich** [comment]
1) got it
2) feel free to merge if the changes would fit into this repo

**Pull request merged**
