### PR TITLE
Feature/27157 skip commented sections

### PR DESCRIPTION
**Pull request by askotnica**
Hello,

I added a feature that allows to skip sections of code using certain region-like comments. Issue: #211 

During testing I noticed, a bug where it actually still adds pre/suffixes to commented lines.

### CODE REVIEW

**Comment by Lazys** [comment]
It's connected to the issue https://github.com/waldo1001/crs-al-language-extension/issues/211

**Comment by Lazys** [comment]
It's reated to the issue https://github.com/waldo1001/crs-al-language-extension/issues/211

**Comment by waldo1001** [comment]
First of all - thanks a lot for the contribution!

I'm not sure this will work with all scenarios - so I'm going to have to thoroughly test this.  I didn't see extra tests - like one that confirms that the code actually has the intended behavior.. ?

**Comment by Lazys** [comment]
Hi, I'm replying on behalf of my colleague :)

Basically that was really important for us because of the reasons mentioned in the issue and incoming go lives - I'm sure that you undersand our pain :D 

Unfortunately we're not really fluent with VS Code extensions and JS ecosystem.

For that reason we just did what we needed and tested it manually without automated tests. We also didn't manage to run already prepared tests - we had really limited time to do so and not enough skills, I guess.

As we managed to obtain the result we needed (or at least we think we managed) we decided to show you this as a kind of an idea. We're totally aware that the code is not fully ready to be merged into master in such state. On the other hand I'm not sure we will have time available to finish this in 100% :/

If you're able to take over it, that would be really great.

**Comment by waldo1001** [comment]
I manually added these changes to the extension as I wanted to thoroughly test them, and implement automated testing as well .. .  So I'll close this Pullrequest, but do know I'm very grateful, and your changes ARE part of the product!

**Comment by Lazys** [comment]
I'm really glad to hear that!

I've just downloded the newest version of your extension and it looks perfect, working as expected :)

I don't want to sound like an idiot, but I really admire the huge amout of your contribiution to the community. Respect!

Thanks again :)

**Comment by waldo1001** [comment]
I really appreciate that - thanks so much 👍 
We have a very strong community - and people like you guys prove that every single day! 🙏

**Pull request closed without merging**
