### PR TITLE
Reorganize By Namespace

### PR DESCRIPTION
**Pull request by Spycoclown**
#291 
This is a feature that allows for the automatic reorganization of files by creating folder structures based on the namespaces defined within the files.

### CODE REVIEW

**Comment by Spycoclown** [comment]
On thing i was thinking about, should the folder names be fix lowercase?

**Comment by Spycoclown** [comment]
@waldo1001 i don't know how to forward that PR? can you help me here?

**Comment by Spycoclown** [comment]
@christianbraeunlich @jwikman I hope one of you two can help me. How do I proceed with this Pull Request now?

**Comment by jwikman** [comment]
@Spycoclown I cannot do much, I'm afraid.
Only @waldo1001 can merge PR's.

Just a quick comment from my side, don't leave unnecessary comments in the code. ;-)

**Comment by waldo1001** [comment]
First of all - thanks SO MUCH for this PR.  I'll try to handle this today ..

**Review by waldo1001 — APPROVED** [review]

**Comment by vdevmt** [comment]
This is a wonderful update!
It is possibile to exclude a part of namespace from this function?
We usually create a namespace with this format:
<Customer>.<ApplicationName>.<Area>.<SubArea>
(e.g. Contoso.BaseApplication.Sales.Customer)
So I would like to exclude the first two parts from the reorganization function.

**Comment by vdevmt** [comment]
Yes, I know :(
Don't worry, I'll wait to hear from you.

**Pull request merged**
