### PR TITLE
Adding CI/CD

### PR DESCRIPTION
**Pull request by christianbraeunlich**
This (Draft) PR attempts to add a CI/CD pipeline to this project.

This includes the following tasks:

- [x] Build
- [x] Lint
- [x] Test
- [x] Release and Publish

What do you think? (Here is a first test run https://github.com/christianbraeunlich/crs-al-language-extension/actions/runs/2309049391)

### CODE REVIEW

**Comment by waldo1001** [comment]
I remember that I spent quite some time on it back in the days (in DevOps) .. but my knowledge in anything typescript is limited .. too limited back then.

that said - would LOVE to look into that again!

On top of that - It would be awesome that it would also run the tests ;-).

**Comment by christianbraeunlich** [comment]
I'm totally with you on that point. Maybe we can discuss a few things before we add this to the main release - especially for the release/launch step, I would want to know how you want to handle this.

**Comment by waldo1001** [comment]
Let's do that!
Totally appreciate your contribution on this - it's been too busy for me to do anything useful lately, so this is very much appreciated!

**Comment by christianbraeunlich** [comment]
The artifact is +12 MB... I need to provide a `.vscodeignore` file to reduce the size.

**Comment by waldo1001** [comment]
Woopsie .. 

I was able to reduce it - it's in the master branch!

**Comment by christianbraeunlich** [comment]
Here's a brief introduction to what the workflow is doing:
a) Whenever there is a push into this repo the pipeline gets triggered and runs Lint, Test and Build.
b) Whenever there is a push of a tag to the repo it will now also get into the Release job which involves the following steps:
1. checking the tag (e.g. v1.5.6) matching the version number in the package.json (e.g. "version": "1.5.6"). In this case there is a match and the pipeline continues (otherwise an error will occure).
2. The vs-code package will be published to the marketplace
3. Reading the section from the changelog.md file with all the lines underneath e.g. [1.5.6] - dd.MM.yy
4. Creating a GitHub Release and storing the changelog section into that body.
5. Upload the artifact to the GitHub release

Requirement:
- you need to provide a secret called `VSCE_TOKEN` with the permission Marketplace (Azure DevOps / PAT .. the usual kind of thing)

What do you think of the current state of the pipeline? We could optimize it along the road or implement some changes right away.
Let me know if this is what you've had in mind. We are now triggering the release/publish process manually by pushing a tag to the repository.

**Comment by christianbraeunlich** [comment]
I changed the state back to Draft as I think we should spend a bit more time on this.

In the meantime I create a sample project to have some sort of playground for myself. Have a look at the workflow "Create Release" (https://github.com/christianbraeunlich/chewbacca/actions/workflows/createRelease.yml). This would make it possible to create a release manually from GitHub.

As I'm not happy with the workflows atm, I will spend some more time on them next week :)

**Comment by christianbraeunlich** [comment]
> Already looking pretty good - you need anything from me?

You could create a PAT in Azure DevOps with Marketplace rights and put that into a secret (e.g. called "VSCE_TOKEN") for this repository.

I'll get to this PR next week as I'm moving into a new apartment this week.

**Comment by waldo1001** [comment]
> > Already looking pretty good - you need anything from me?
> 
> You could create a PAT in Azure DevOps with Marketplace rights and put that into a secret (e.g. called "VSCE_TOKEN") for this repository.
> 
> I'll get to this PR next week as I'm moving into a new apartment this week.

VSCE_TOKEN has been added!

**Comment by christianbraeunlich** [comment]
Yeah, still potential for improvements - feel free to review. Want to create the first release together just pm me via discord

**Review by waldo1001 — APPROVED** [review]

**Pull request merged**
