### PR TITLE
Insert next available ObjectID

### PR DESCRIPTION
**Pull request by jwikman**
Hi @waldo1001,

Let me know if you don't think that this PR fits in your extension, then I'll put it in a new extension instead. Now that I know how to do it. ;-)

The concept of the feature is quite simple: It looks at the idRange in app.json and existing al-files to find the next available Object Id for that object type.

Known limitation: I only check idRange, not idRanges. So if one uses idRanges it won't work. I don't know how common this is (yet), but I simply did not have the time to fix this at the moment.

Cheers,
Johannes

### CODE REVIEW

**Comment by waldo1001** [comment]
Hi @jwikman , I have no problem adding it (for which a big thanks again! :-))

but can you please tell me what the problem is that you are trying to solve?  Probably a bad question, but still ;-).  How is this different than the "automatic object numbering" that comes with the compiler?

**Comment by jwikman** [comment]
@waldo1001 haha, just reject this PR, ok?!

I didn't know that (but I have read your blog post about it, obviously forgot about it). I even asked a few colleagues on how they picked the next number - And I've seen some different manual solutions to the (non-existent) problem.

It's just as you state in your blog post, a somewhat hidden feature.

At least I learnt some more TypeScript while doing this. ;-)

**Comment by waldo1001** [comment]
:-) Lol ... ok .. so I did understand it ;-)

**Comment by waldo1001** [comment]
Though - may be it's interesting to use this code and turn it into some kind of "renumber" feature?

**Comment by jwikman** [comment]
Use and abuse as you like :)

**Comment by waldo1001** [comment]
I completely forgot about this thing - and since we now have ObjectNinja and such, I guess it's not applicable anymore ;-)

**Comment by jwikman** [comment]
Yes, I don't think we ever need this 😂

**Pull request closed without merging**
